# Generated by Django 6.0.1 on 2026-01-24 18:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Manifesto Content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='The Senior Addendum', max_length=255, verbose_name='Site Title'),
        ),
    ]
