# Generated by Django 6.0.1 on 2026-01-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body_alter_homepage_hero_text'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='health_tile_header',
            field=models.CharField(default='Health & Vitality', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='health_tile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='health_tile_text',
            field=models.TextField(blank=True, help_text='Small directory text for the Health tile'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tile_header',
            field=models.CharField(default='The Heroes', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tile_text',
            field=models.TextField(blank=True, help_text='Small directory text for the Hero tile'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tech_tile_header',
            field=models.CharField(default='The Shield', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tech_tile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tech_tile_text',
            field=models.TextField(blank=True, help_text='Small directory text for the Tech tile'),
        ),
    ]
