# Generated by Django 6.0.1 on 2026-02-15 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('discount_percent', models.IntegerField(default=0, help_text='Percentage off (0-100)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed dollar amount off', max_digits=6)),
                ('grants_free_days', models.IntegerField(default=0, help_text='Days of free access')),
                ('grants_tier', models.CharField(blank=True, choices=[('free', 'Free'), ('member', 'Member'), ('premium', 'Premium')], help_text='Tier to grant during free trial', max_length=20, null=True)),
                ('max_uses', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('times_used', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('member', 'Member'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('can_play_ai_opponents', models.BooleanField(default=False)),
                ('can_play_claude_ai', models.BooleanField(default=False)),
                ('games_per_day_limit', models.IntegerField(default=5, help_text='0 = unlimited')),
                ('show_ads', models.BooleanField(default=True)),
                ('monthly_poem_tokens', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('member', 'Member'), ('premium', 'Premium')], default='free', max_length=20)),
                ('is_member', models.BooleanField(default=False, help_text='True if user has any paid subscription')),
                ('subscription_started', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('experience_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('poem_tokens_remaining', models.IntegerField(default=0)),
                ('games_played_today', models.IntegerField(default=0)),
                ('last_game_reset', models.DateField(default=django.utils.timezone.now)),
                ('scrabble_seen_blank_tooltip', models.BooleanField(default=False)),
                ('scrabble_seen_challenge_tutorial', models.BooleanField(default=False)),
                ('scrabble_seen_exchange_tutorial', models.BooleanField(default=False)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_games_won', models.IntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for support/billing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='members.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Player Profile',
                'verbose_name_plural': 'Player Profiles',
            },
        ),
    ]
